apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-news
  template:
    metadata:
      labels:
        app: frontend-news
    spec:
      containers:
        - name: frontend-news
          image: frontend-news:latest 
          imagePullPolicy: Never  # Use the same image name from Docker
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-news-service
spec:
  selector:
    app: frontend-news
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Expose service on a port accessible externally
